Repository astronomer/astronomer, pull requests merged in 2018-04, with the labels that each got.

#49 Pin setuptools for deterministic build
  docker/platform/airflow/Dockerfile
Labels: 5: Improvement

#50 Upgrade + pin pip to 9.0.3
  docker/platform/airflow/Dockerfile
Labels: 5: Improvement

#39 Update Airflow examples docs
  docs/pages/airflow.md
  examples/airflow-core/.env
  examples/airflow-core/airflow.env
  examples/airflow-core/docker-compose.yml
  examples/airflow-core/initdb.sql
Labels: 4: Milestone Focus

#56 Pin Grafana to 5.0.4
  docker/vendor/grafana/Dockerfile
Labels: 5: Improvement

#71 Use astro branding for docs
  docs/_config.yml
  docs/_includes/footer.html
  docs/_includes/head.html
  docs/_includes/jumbotron.html
  docs/assets/css/styles.scss
  docs/assets/img/astro.ico
  docs/assets/img/stars-bg.png
  docs/assets/js/docs.min.js
Labels: 5: Improvement

#72 External links fix (Open)
  docs/_includes/head.html
Labels: 1: Support/Bug

#73 Update dependencies to fix nokogiri vulnerability in local docs site
  docs/Gemfile.lock
Labels: 5: Improvement
