Repository astronomer/astronomer, pull requests merged in 2020-08, with the labels that each got.

#809 Fix a few places where release name and namespace were conflated
  Makefile
  charts/elasticsearch/templates/es-psp-rolebinding.yaml
  charts/fluentd/templates/fluentd-psp-rolebinding.yaml
  charts/nginx/templates/nginx-psp-rolebinding.yaml
  charts/prometheus/templates/prometheus-alerts-configmap.yaml
  charts/stan/templates/statefulset.yaml
Labels: backport0.16

#800 Fix Houston API pod disruption budget to not match Houston cron jobs
  charts/astronomer/templates/houston/cronjobs/houston-check-updates-cronjob.yaml
  charts/astronomer/templates/houston/cronjobs/houston-expire-deployments-cronjob.yaml
  charts/astronomer/templates/houston/cronjobs/houston-upgrade-deployments-job.yaml
  charts/astronomer/tests/houston_pdb_test.yaml
Labels: backport0.16

#811 Fix scrape configuration for blackbox exporter
  charts/prometheus/templates/prometheus-config-configmap.yaml
  charts/prometheus/templates/prometheus-statefulset.yaml
  charts/prometheus/tests/prometheus-config-configmap_test.yaml
Labels: backport0.16

#818 Allow for user-supplied values in prometheus alerts configmap
  Makefile
  charts/prometheus/templates/prometheus-alerts-configmap.yaml
  charts/prometheus/templates/prometheus-statefulset.yaml
  charts/prometheus/tests/prometheus-alerts-configmap_test.yaml
  charts/prometheus/values.yaml
Labels: area/prometheus, backport0.16

#821 Fix network policy to allow houston upgrader to connect to DB
  bin/install-platform
  charts/astronomer/templates/commander/commander-networkpolicy.yaml
  charts/astronomer/templates/prisma/prisma-networkpolicy.yaml
  charts/astronomer/templates/registry/registry-networkpolicy.yaml
Labels: backport0.16, backport0.19
