Repository astronomer/astronomer, pull requests merged in 2022-02, with the labels that each got.

#1361 Bump image versions in nats and stan
  charts/nats/values.yaml
  charts/stan/values.yaml
Labels: 0.28.0, 0.25.13, 0.27.2, 0.26.7

#1297 Fix a bunch of hard-coded strings that had templates defined.
  charts/astronomer/templates/commander/commander-role.yaml
  charts/astronomer/templates/houston/api/houston-bootstrap-role.yaml
  charts/astronomer/templates/houston/api/houston-bootstrap-rolebinding.yaml
  charts/astronomer/templates/houston/helm-hooks/houston-db-migration-job.yaml
  charts/astronomer/templates/houston/helm-hooks/houston-upgrade-deployments-job.yaml
  charts/astronomer/templates/istio/sidecars.yaml
  charts/elasticsearch/templates/es-psp-clusterrole.yaml
  charts/elasticsearch/templates/es-psp-rolebinding.yaml
  charts/fluentd/templates/fluentd-clusterrole.yaml
  charts/fluentd/templates/fluentd-clusterrolebinding.yaml
  charts/fluentd/templates/fluentd-psp-clusterrole.yaml
  charts/fluentd/templates/fluentd-psp-rolebinding.yaml
  charts/grafana/templates/grafana-bootstrap-role.yaml
  charts/grafana/templates/grafana-bootstrap-rolebinding.yaml
  charts/kube-state/templates/kube-state-role.yaml
  charts/kube-state/templates/kube-state-rolebinding.yaml
  charts/kubed/templates/kubed-apiregistration.yaml
  charts/kubed/templates/kubed-clusterrole.yaml
  charts/kubed/templates/kubed-clusterrolebinding.yaml
  charts/kubed/templates/kubed-user-roles.yaml
  charts/nginx/templates/nginx-config-role.yaml
  charts/nginx/templates/nginx-config-rolebinding.yaml
  charts/nginx/templates/nginx-psp-clusterrole.yaml
  charts/nginx/templates/nginx-psp-rolebinding.yaml
  charts/nginx/templates/nginx-role.yaml
  charts/nginx/templates/nginx-rolebinding.yaml
  charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
  charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
  charts/prometheus/templates/prometheus-role.yaml
  charts/prometheus/templates/prometheus-rolebinding.yaml
  templates/_apivers.tpl
  templates/psp/permissive-clusterrole.yaml
  templates/psp/permissive-clusterrolebinding.yaml
  templates/psp/restrictive-cluserrolebinding.yaml
  templates/psp/restrictive-clusterrole.yaml
  templates/trust-private-ca-on-all-nodes/psp-clusterrole.yaml
  templates/trust-private-ca-on-all-nodes/psp-rolebinding.yaml
Labels: 0.28.0

#1379 backport ap-vendor security fixes to release-0.27
  charts/astronomer/values.yaml
  charts/elasticsearch/templates/data/es-data-statefulset.yaml
  charts/elasticsearch/templates/master/es-master-statefulset.yaml
  charts/elasticsearch/values.yaml
  charts/grafana/values.yaml
  charts/kibana/values.yaml
  charts/nginx/values.yaml
  charts/prometheus/values.yaml
  tests/test_cves.py
Labels: 0.27.3
